# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ v1.0-dev ]
  pull_request:
    branches: [ v1.0-dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package -Dmaven.test.skip=true --file ccgame-service/pom.xml
#       - run: mkdir staging && cp ccgame-service/target/*.jar staging
#       - uses: actions/upload-artifact@v2
#         with:
#           name: Packing
#           path: staging
